name: Build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Compile project
        run: mvn compile
      - name: Clean project
        run: mvn clean

  test:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Test project
        run: mvn test
      - name: Clean project
        run: mvn clean
